version: "3"

services:
  backend:
    build: .
    volumes:
      - ./project:/app # maps host diretory to internal container directory
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000